baseurl = "http://www.c25k.io/"
languageCode = "en-us"
title = "C25Kio - Start Running"
canonifyurls = true

[params]
  description = "You want to start running regularly, but don't know where to start? Simple running programs and tips are here for you. Start a running routine with the support of C25K."
